package com.attendai.attendance.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Stores a prototype biometric face descriptor for an employee.
 *
 * ⚠ PROTOTYPE / DEMO FEATURE:
 * This implementation stores a 128-element float vector generated by a
 * browser-side face descriptor library. Comparison is performed using
 * Euclidean distance — this is NOT production-grade biometric security.
 * The service is isolated so it can be replaced with a proper biometric
 * provider (e.g. AWS Rekognition, Azure Face API) in production.
 *
 * Raw camera images are NEVER stored. Only the derived float descriptor is stored.
 * Face descriptors are NEVER exposed in normal API responses.
 */
@Getter
@Setter
@Entity
@Table(name = "face_profiles")
public class FaceProfile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** References employee-service Employee.id — no cross-service FK. */
    @Column(nullable = false, unique = true)
    private Long employeeId;

    /**
     * JSON-serialized float array (length 128) representing the face descriptor.
     * Generated by browser-side face landmark detection — NOT a raw image.
     * Never exposed via API responses.
     */
    @Column(columnDefinition = "TEXT", nullable = false)
    private String faceDescriptor;

    @Column(nullable = false)
    private boolean isEnrolled = true;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private Instant updatedAt;
}
